added forgot password feature
vikasdo/Book-Recommendation-Analysis pull request #37
Opened 2021-03-20 10:35 UTC by VishvamPorwal

# Description

Added forgot password feature as described in the issue.
Closes #22 

## Type of change

Added forgot password feature.

# How Has This Been Tested?

Tried this feature with multiple emails.

2021-03-20 14:00 UTC, Akshay6890 requested changes

2021-03-20 14:09 UTC, VishvamPorwal commented on bookstore/client/views.py
> +            return redirect(url_for("otp"))
fixed it, sorry about that I guess I forgot about it.

2021-03-20 14:26 UTC, VishvamPorwal commented on bookstore/client/views.py
> +        session["cli_email"] = email
Pardon me, but I am not getting your point, how would user login if they dont remember there password.

2021-03-21 03:29 UTC, Akshay6890 commented
hey that session comment was a mistake, you did it right :)

On Sat, Mar 20, 2021, 7:56 PM Vishvam Porwal ***@***.***>
wrote:

> *@VishvamPorwal* commented on this pull request.
> ------------------------------
>
> In bookstore/client/views.py
> <https://github.com/vikasdo/Book-Recommendation-Analysis/pull/37#discussion_r598118053>
> :
>
> > @@ -388,3 +389,60 @@ def discounts():
>      db.session.commit()
>      flash(f'Discount Successfully Updated','success')
>      return redirect(url_for('personalized_offers'))
> +
> +
> ***@***.***("/forgotpwd", methods=["POST", "GET"])
> +def forgotpwd():
> +    if request.method == "GET":
> +        return render_template("client/forgot_password.html")
> +    else:
> +        email = request.form.get("email")
> +        session["cli_email"] = email
>
> Pardon me, but I am not getting your point, how would user login if they
> dont remember there password.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/vikasdo/Book-Recommendation-Analysis/pull/37#discussion_r598118053>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALH7ATYBBWSQMZOBOGDHANDTESWDDANCNFSM4ZQJSKEQ>
> .
>

2021-03-21 04:50 UTC, Akshay6890 commented on bookstore/client/views.py
> +        session["cli_email"] = email
> Hey, ignore that session, it was my mistake :)

2021-03-21 09:05 UTC, VishvamPorwal commented
I have made some commits to fix every issue.

2021-03-21 09:06 UTC, Akshay6890 commented
Ok, this looks great!

2021-03-21 09:09 UTC, Akshay6890 approved these changes
This is great!

2021-03-22 02:39 UTC, merged

2021-04-02 08:43 UTC, VishvamPorwal commented
I did not receive any marks from this pr.